name: fontify
version: 0.0.1-dev
description: >-
  TTF font generator from SVG images
homepage: https://github.com/westracer/fontify

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.7