name: fontify
version: 0.0.1-dev
description: >-
  TTF font generator from SVG images
homepage: https://github.com/westracer/fontify

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  meta: 1.1.8
  xml: 4.2.0
  path: 1.7.0
  path_parsing: 0.1.4
  vector_math: 2.0.8
  logger: 0.9.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.7