name: fontify_plus
version: 0.4.0
description: >-
  Converts SVG icons to OTF font and generates Flutter-compatible class.
  Provides an API and a CLI tool.
homepage: https://github.com/4akloon/fontify_plus

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.6.0
  collection: ^1.19.0
  logger: ^2.4.0
  meta: ^1.16.0
  path: ^1.9.0
  path_parsing: ^1.0.1
  recase: ^4.1.0
  vector_math: ^2.1.4
  xml: ^6.5.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^5.1.0
  test: ^1.25.8
  
executables:
  fontify_plus: fontify_plus_plus